{
    "POSTS_DIRECTORY": "_posts",
    "LAYOUTS_DIRECTORY": "_layouts",

    "BLOG_URL": "http://example.com",
    "BLOG_TITLE": "Example blog",
    "BLOG_DESCRIPTION": "Static blog generated by Plankton"
}